version: '3'

services:

    server:
        build: .
        container_name: grpc_container
        ports: 
            - 3000:3000

    client:
        build: ./client
        container_name: python_container
        ports: 
            - 5000:5000
        depends_on:  
            - server
